import { BadRequestException, Injectable } from '@nestjs/common';
import {
  generateSanitaryCalendar,
  sanitaryEventAlert,
  type SanitaryCalendarRule
} from '@ferm-plus/domain-rules';
import { type SessionUser } from '../auth/auth.service.js';
import { FarmsService } from '../farms/farms.service.js';
import { ReminderService } from '../notifications/reminder.service.js';
import { PrismaService } from '../shared/database/prisma.service.js';

export interface SanitaryEventView {
  id: string;
  animalGroupId: string | null;
  animalLabel: string | null;
  eventType: 'MALADIE' | 'VACCINATION' | 'TRAITEMENT' | 'CONSULTATION' | 'MORTALITE' | 'CONTROLE';
  eventDate: string;
  status: 'PLANIFIE' | 'EN_COURS' | 'TERMINE' | 'CRITIQUE';
  isAutoGenerated: boolean;
  protocolLabel: string | null;
  notes: string;
  recordedByUserName: string;
}

@Injectable()
export class SanitaryService {
  constructor(
    private readonly farmsService: FarmsService,
    private readonly prisma: PrismaService,
    private readonly reminderService: ReminderService
  ) {}

  async listEvents(user: SessionUser, farmId: string) {
    const farm = await this.farmsService.getFarm(user, farmId);
    await this.ensureAutomaticCalendarForFarm(farm.id, user.id);
    const items = await this.prisma.sanitaryEvent.findMany({
      where: { farmId: farm.id },
      include: {
        animalGroup: {
          select: {
            identificationNumber: true,
            species: true
          }
        },
        recordedByUser: {
          select: { fullName: true }
        }
      },
      orderBy: [{ eventDate: 'desc' }, { createdAt: 'desc' }]
    });

    return {
      items: items.map((item) => ({
        id: item.id,
        animalGroupId: item.animalGroupId,
        animalLabel: item.animalGroup
          ? `${item.animalGroup.identificationNumber} - ${item.animalGroup.species}`
          : null,
        eventType: item.eventType,
        eventDate: item.eventDate.toISOString(),
        status: item.status,
        isAutoGenerated: item.isAutoGenerated,
        protocolLabel: item.protocolLabel,
        notes: item.notes,
        recordedByUserName: item.recordedByUser.fullName
      }))
    };
  }

  async createEvent(
    user: SessionUser,
    farmId: string,
    input: {
      animalGroupId?: string;
      eventType: SanitaryEventView['eventType'];
      eventDate: string;
      status: SanitaryEventView['status'];
      notes?: string;
    }
  ) {
    const farm = await this.farmsService.getFarm(user, farmId);
    const eventDate = new Date(input.eventDate);

    if (Number.isNaN(eventDate.getTime())) {
      throw new BadRequestException("Date d'evenement invalide");
    }

    if (input.animalGroupId) {
      await this.prisma.animalGroup.findFirstOrThrow({
        where: {
          id: input.animalGroupId,
          farmId: farm.id
        }
      });
    }

    const created = await this.prisma.sanitaryEvent.create({
      data: {
        farmId: farm.id,
        animalGroupId: input.animalGroupId || null,
        eventType: input.eventType,
        eventDate,
        status: input.status,
        notes: input.notes?.trim() || '',
        recordedByUserId: user.id
      },
      include: {
        animalGroup: {
          select: {
            identificationNumber: true,
            species: true
          }
        },
        recordedByUser: {
          select: { fullName: true }
        }
      }
    });

    await this.ensureAgendaTaskForManualSanitaryEvent({
      farmId: farm.id,
      sanitaryEventId: created.id,
      animalLabel: created.animalGroup
        ? `${created.animalGroup.identificationNumber} - ${created.animalGroup.species}`
        : null,
      eventType: created.eventType,
      eventDate: created.eventDate,
      status: created.status,
      notes: created.notes
    });

    const sanitaryAlert = sanitaryEventAlert({
      species: created.animalGroup?.species ?? null,
      eventType: created.eventType,
      eventDate: created.eventDate,
      status: created.status,
      notes: created.notes,
      label: created.animalGroup
        ? `${created.eventType} - ${created.animalGroup.identificationNumber}`
        : created.eventType
    });

    if (sanitaryAlert) {
      await this.prisma.alert.create({
        data: {
          farmId: farm.id,
          priority: sanitaryAlert.type === 'CRITICAL' ? 'URGENT' : 'HIGH',
          title: sanitaryAlert.title,
          severity: sanitaryAlert.type,
          message: sanitaryAlert.message,
          sourceModule: 'SANITAIRE',
          sourceRecordId: created.id
        }
      });
    }

    return {
      id: created.id,
      animalGroupId: created.animalGroupId,
        animalLabel: created.animalGroup
        ? `${created.animalGroup.identificationNumber} - ${created.animalGroup.species}`
        : null,
      eventType: created.eventType,
      eventDate: created.eventDate.toISOString(),
      status: created.status,
      isAutoGenerated: created.isAutoGenerated,
      protocolLabel: created.protocolLabel,
      notes: created.notes,
      recordedByUserName: created.recordedByUser.fullName
    };
  }

  async ensureAutomaticCalendarForFarm(farmId: string, automationUserId: string) {
    const animalGroups = await this.prisma.animalGroup.findMany({
      where: {
        farmId,
        status: 'ACTIF'
      }
    });

    for (const animalGroup of animalGroups) {
      await this.ensureAutomaticCalendarForAnimalGroup({
        farmId,
        animalGroupId: animalGroup.id,
        identificationNumber: animalGroup.identificationNumber,
        species: animalGroup.species,
        subtype: animalGroup.subtype,
        breed: animalGroup.breed,
        birthDate: animalGroup.birthDate,
        currentAgeDays: animalGroup.currentAgeDays
      }, automationUserId);
    }
  }

  async ensureAutomaticCalendarForAnimalGroup(
    animalGroup: {
      farmId: string;
      animalGroupId: string;
      identificationNumber: string;
      species: string;
      subtype: string;
      breed: string;
      birthDate: Date;
      currentAgeDays: number;
    },
    automationUserId: string
  ) {
    const rules = generateSanitaryCalendar({
      species: animalGroup.species,
      subtype: animalGroup.subtype,
      breed: animalGroup.breed,
      currentAgeDays: animalGroup.currentAgeDays
    });

    for (const rule of rules) {
      const eventDate = new Date(animalGroup.birthDate);
      eventDate.setDate(eventDate.getDate() + rule.offsetDays);

      const originKey = `${animalGroup.animalGroupId}:${rule.ruleCode}:${eventDate.toISOString().slice(0, 10)}`;

      const existingEvent = await this.prisma.sanitaryEvent.findFirst({
        where: {
          farmId: animalGroup.farmId,
          animalGroupId: animalGroup.animalGroupId,
          originKey
        }
      });

      const event =
        existingEvent ??
        (await this.prisma.sanitaryEvent.create({
          data: {
            farmId: animalGroup.farmId,
            animalGroupId: animalGroup.animalGroupId,
            eventType: rule.eventType,
            eventDate,
            status: 'PLANIFIE',
            isAutoGenerated: true,
            protocolLabel: rule.protocolLabel,
            originKey,
            notes: `${rule.label} - ${rule.notes}`,
            recordedByUserId: automationUserId
          }
        }));

      await this.ensureAgendaTaskForSanitaryEvent(animalGroup, event.id, eventDate, rule);
    }
  }

  private async ensureAgendaTaskForSanitaryEvent(
    animalGroup: {
      farmId: string;
      identificationNumber: string;
      species: string;
    },
    sanitaryEventId: string,
    eventDate: Date,
    rule: SanitaryCalendarRule
  ) {
    const existingTask = await this.prisma.agendaTask.findFirst({
      where: {
        farmId: animalGroup.farmId,
        sourceModule: 'SANITARY_AUTO',
        sourceRecordId: sanitaryEventId
      }
    });

    const agendaPayload = {
      title: `${rule.label} - ${animalGroup.identificationNumber}`,
      description: `${rule.notes} (${animalGroup.species})`,
      priority: rule.priority,
      status: eventDate.getTime() < Date.now() ? 'EN_RETARD' : 'A_FAIRE',
      scheduledFor: eventDate,
      scheduledLabel: this.formatScheduledLabel(eventDate),
      sourceModule: 'SANITARY_AUTO',
      sourceRecordId: sanitaryEventId
    } as const;

    const task = existingTask
      ? await this.prisma.agendaTask.update({
          where: { id: existingTask.id },
          data: agendaPayload
        })
      : await this.prisma.agendaTask.create({
          data: {
            farmId: animalGroup.farmId,
            ...agendaPayload
          }
        });

    await this.reminderService.syncTaskReminders(task);
  }

  private async ensureAgendaTaskForManualSanitaryEvent(event: {
    farmId: string;
    sanitaryEventId: string;
    animalLabel: string | null;
    eventType: SanitaryEventView['eventType'];
    eventDate: Date;
    status: SanitaryEventView['status'];
    notes: string;
  }) {
    const existingTask = await this.prisma.agendaTask.findFirst({
      where: {
        farmId: event.farmId,
        sourceModule: 'SANITARY_MANUAL',
        sourceRecordId: event.sanitaryEventId
      }
    });

    const title = `${this.formatManualEventLabel(event.eventType)}${event.animalLabel ? ` - ${event.animalLabel}` : ''}`;
    const description = event.notes || `Suivi sanitaire manuel: ${this.formatManualEventLabel(event.eventType)}.`;

    const payload = {
      title,
      description,
      priority: this.toAgendaPriority(event.eventType, event.status),
      status: this.toAgendaStatus(event.eventDate, event.status),
      scheduledFor: event.eventDate,
      scheduledLabel: this.formatScheduledLabel(event.eventDate),
      sourceModule: 'SANITARY_MANUAL',
      sourceRecordId: event.sanitaryEventId
    } as const;

    const task = existingTask
      ? await this.prisma.agendaTask.update({
          where: { id: existingTask.id },
          data: payload
        })
      : await this.prisma.agendaTask.create({
          data: {
            farmId: event.farmId,
            ...payload
          }
        });

    await this.reminderService.syncTaskReminders(task);
  }

  private formatManualEventLabel(eventType: SanitaryEventView['eventType']) {
    switch (eventType) {
      case 'VACCINATION':
        return 'Vaccination programmee';
      case 'TRAITEMENT':
        return 'Traitement preventif';
      case 'CONSULTATION':
        return 'Consultation sanitaire';
      case 'CONTROLE':
        return 'Controle sanitaire';
      case 'MORTALITE':
        return 'Verification mortalite';
      case 'MALADIE':
        return 'Suivi maladie';
      default:
        return 'Intervention sanitaire';
    }
  }

  private toAgendaPriority(
    eventType: SanitaryEventView['eventType'],
    status: SanitaryEventView['status']
  ): 'LOW' | 'MEDIUM' | 'HIGH' {
    if (status === 'CRITIQUE' || eventType === 'MORTALITE' || eventType === 'VACCINATION') {
      return 'HIGH';
    }

    if (eventType === 'TRAITEMENT' || eventType === 'CONSULTATION') {
      return 'MEDIUM';
    }

    return 'LOW';
  }

  private toAgendaStatus(
    eventDate: Date,
    status: SanitaryEventView['status']
  ): 'A_FAIRE' | 'EN_COURS' | 'TERMINEE' | 'EN_RETARD' {
    if (status === 'TERMINE') {
      return 'TERMINEE';
    }

    if (status === 'EN_COURS') {
      return 'EN_COURS';
    }

    if (status === 'CRITIQUE' || eventDate.getTime() < Date.now()) {
      return 'EN_RETARD';
    }

    return 'A_FAIRE';
  }

  private formatScheduledLabel(date: Date) {
    const startOfToday = new Date();
    startOfToday.setHours(0, 0, 0, 0);

    const startOfTomorrow = new Date(startOfToday);
    startOfTomorrow.setDate(startOfTomorrow.getDate() + 1);

    const startOfTarget = new Date(date);
    startOfTarget.setHours(0, 0, 0, 0);

    if (startOfTarget.getTime() === startOfToday.getTime()) {
      return "Aujourd'hui";
    }

    if (startOfTarget.getTime() === startOfTomorrow.getTime()) {
      return 'Demain';
    }

    if (startOfTarget.getTime() < startOfToday.getTime()) {
      return 'En retard';
    }

    return date.toLocaleDateString('fr-FR');
  }
}
