'use client';

import { motion } from 'framer-motion';
import { HeartPulse, ShieldAlert, ShieldCheck, Syringe } from 'lucide-react';
import { useEffect, useMemo, useState, useTransition } from 'react';
import { AppShell } from '../../../../components/app-shell';
import { Badge } from '../../../../components/ui/badge';
import { Button } from '../../../../components/ui/button';
import { useSession } from '../../../../hooks/use-session';
import {
  createSanitaryEvent,
  getFarm,
  getFarmAnimalGroups,
  getFarmSanitaryEvents,
  syncSanitaryCalendar,
  type AnimalGroupView,
  type SanitaryEventView
} from '../../../../services/farm-client';

type SanitaryFormState = {
  animalGroupId: string;
  eventType: SanitaryEventView['eventType'];
  eventDate: string;
  status: SanitaryEventView['status'];
  notes: string;
};

const defaultForm: SanitaryFormState = {
  animalGroupId: '',
  eventType: 'VACCINATION',
  eventDate: new Date().toISOString().slice(0, 10),
  status: 'PLANIFIE',
  notes: ''
};

function sanitaryBadge(status: SanitaryEventView['status']) {
  if (status === 'TERMINE') {
    return 'success' as const;
  }

  if (status === 'CRITIQUE') {
    return 'critical' as const;
  }

  if (status === 'EN_COURS') {
    return 'warning' as const;
  }

  return 'info' as const;
}

const sanitaryWorkflowSteps = [
  {
    title: 'Prévention',
    description: 'Planifier les vaccinations et rappels importants.',
    icon: Syringe
  },
  {
    title: 'Suivi',
    description: 'Associer chaque acte au lot ou à l’animal concerné.',
    icon: HeartPulse
  },
  {
    title: 'Alerte',
    description: 'Repérer les situations critiques sans délai.',
    icon: ShieldAlert
  },
  {
    title: 'Calendrier',
    description: 'Synchroniser automatiquement les protocoles sanitaires.',
    icon: ShieldCheck
  }
] as const;

export default function FarmSanitaryPage({
  params
}: {
  params: Promise<{ farmId: string }>;
}) {
  const session = useSession();
  const [isPending, startTransition] = useTransition();
  const [farmId, setFarmId] = useState('');
  const [farmName, setFarmName] = useState('Ferme');
  const [events, setEvents] = useState<SanitaryEventView[]>([]);
  const [animals, setAnimals] = useState<AnimalGroupView[]>([]);
  const [form, setForm] = useState<SanitaryFormState>(defaultForm);
  const [error, setError] = useState<string | null>(null);

  function refresh(activeFarmId: string, token: string) {
    return Promise.all([getFarmSanitaryEvents(activeFarmId, token), getFarmAnimalGroups(activeFarmId, token)]).then(
      ([eventResponse, animalResponse]) => {
        setEvents(eventResponse.items);
        setAnimals(animalResponse.items);
      }
    );
  }

  useEffect(() => {
    params.then((value) => setFarmId(value.farmId));
  }, [params]);

  useEffect(() => {
    if (!session?.token || !farmId) {
      return;
    }

    getFarm(farmId, session.token)
      .then((farm) => setFarmName(farm.name))
      .catch(() => setFarmName(`Ferme ${farmId}`));

    refresh(farmId, session.token).catch(() => {
      setEvents([]);
      setAnimals([]);
    });
  }, [farmId, session?.token]);

  const metrics = useMemo(() => {
    const critical = events.filter((item) => item.status === 'CRITIQUE').length;
    const planned = events.filter((item) => item.status === 'PLANIFIE').length;
    const automatic = events.filter((item) => item.isAutoGenerated).length;
    const completed = events.filter((item) => item.status === 'TERMINE').length;

    return { critical, planned, automatic, completed };
  }, [events]);

  function submitEvent(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!session?.token) {
      return;
    }

    setError(null);
    startTransition(async () => {
      try {
        await createSanitaryEvent(
          farmId,
          {
            animalGroupId: form.animalGroupId || undefined,
            eventType: form.eventType,
            eventDate: form.eventDate,
            status: form.status,
            notes: form.notes || undefined
          },
          session.token
        );
        setForm(defaultForm);
        await refresh(farmId, session.token);
      } catch (submissionError) {
        setError(submissionError instanceof Error ? submissionError.message : 'Enregistrement impossible');
      }
    });
  }

  function runCalendarSync() {
    if (!session?.token) {
      return;
    }

    setError(null);
    startTransition(async () => {
      try {
        await syncSanitaryCalendar(farmId, session.token);
        await refresh(farmId, session.token);
      } catch (submissionError) {
        setError(submissionError instanceof Error ? submissionError.message : 'Synchronisation impossible');
      }
    });
  }

  return (
    <AppShell title={`Sanitaire - ${farmName}`}>
      {error ? <p className="error-text">{error}</p> : null}

      <section className="module-hero-grid sanitary-hero-grid sanitary-hero-grid-premium">
        <article className="module-hero-card sanitary-hero-card sanitary-hero-card-premium">
          <div className="module-hero-top">
            <div>
              <p className="eyebrow">Pilotage sanitaire</p>
              <h2 className="module-hero-title">{farmName}</h2>
            </div>
            <Badge variant={metrics.critical > 0 ? 'critical' : 'success'}>
              {metrics.critical > 0 ? `${metrics.critical} critique(s)` : 'Sous controle'}
            </Badge>
          </div>
          <p className="hero-copy module-hero-copy">
            Un centre plus rassurant pour superviser les vaccins, traitements, controles et signaux
            sensibles relies au cheptel.
          </p>
          <div className="module-pill-row">
            <span className="module-detail-chip">
              <HeartPulse className="h-4 w-4" />
              {events.length} evenement(s)
            </span>
            <span className="module-detail-chip">
              <ShieldAlert className="h-4 w-4" />
              {metrics.planned} planifie(s)
            </span>
            <span className="module-detail-chip">
              <Syringe className="h-4 w-4" />
              {metrics.automatic} auto-generes
            </span>
          </div>
          <div className="module-kpi-grid">
            <article className="module-kpi-card">
              <div className="module-kpi-header">
                <div className="module-kpi-icon">
                  <ShieldAlert className="h-5 w-5" />
                </div>
                <Badge variant={metrics.critical > 0 ? 'critical' : 'success'}>Alertes</Badge>
              </div>
              <strong>{metrics.critical}</strong>
              <span>signal(s) critiques qui demandent une attention immediate</span>
            </article>
            <article className="module-kpi-card">
              <div className="module-kpi-header">
                <div className="module-kpi-icon">
                  <Syringe className="h-5 w-5" />
                </div>
                <Badge variant="info">Protocole</Badge>
              </div>
              <strong>{metrics.automatic}</strong>
              <span>entree(s) issues du calendrier sanitaire automatique</span>
            </article>
            <article className="module-kpi-card">
              <div className="module-kpi-header">
                <div className="module-kpi-icon">
                  <ShieldCheck className="h-5 w-5" />
                </div>
                <Badge variant="success">Termines</Badge>
              </div>
              <strong>{metrics.completed}</strong>
              <span>action(s) deja executees et historisees</span>
            </article>
          </div>
        </article>

        <article className="module-spotlight-card sanitary-spotlight-card sanitary-spotlight-card-premium">
          <div className="module-card-top">
            <p className="eyebrow">Registre de sante</p>
            <Badge variant="neutral">{animals.length} lot(s)</Badge>
          </div>
          <h2>Vision claire pour l'equipe et les proprietaires</h2>
          <p>
            Les proprietaires consultent l'historique en lecture, tandis que les administrateurs peuvent
            saisir et synchroniser les protocoles directement depuis cette page.
          </p>
          <div className="module-detail-list">
            <span>Historique manuel et automatique sur une seule ligne de temps</span>
            <span>Les cas critiques nourrissent le centre d'alertes</span>
            <span>Structure prete pour les rappels sanitaires avances</span>
          </div>
        </article>
      </section>

      <section className="module-flow-strip sanitary-flow-strip sanitary-flow-strip-premium">
        {sanitaryWorkflowSteps.map((step, index) => {
          const Icon = step.icon;

          return (
            <article key={step.title} className="module-flow-card">
              <div className="module-card-top">
                <span className="module-flow-index">0{index + 1}</span>
                <Badge variant="neutral">{step.title}</Badge>
              </div>
              <div className="module-kpi-header">
                <div className="module-kpi-icon">
                  <Icon className="h-5 w-5" />
                </div>
              </div>
              <span>{step.description}</span>
            </article>
          );
        })}
      </section>

      {session?.user.role === 'ADMIN' ? (
        <section className="module-action-grid sanitary-action-grid sanitary-action-grid-premium">
          <article className="module-form-card sanitary-form-card sanitary-form-card-premium">
            <div className="dashboard-inline-actions">
              <div>
                <p className="eyebrow">Nouvel evenement sanitaire</p>
                <h2>Declarer une action ou un incident</h2>
              </div>
              <div className="farm-module-icon">
                <HeartPulse className="h-5 w-5" />
              </div>
            </div>
            <form className="stack-form" onSubmit={submitEvent}>
              <div className="field-grid">
                <label className="field">
                  <span>Lot / animal</span>
                  <select
                    value={form.animalGroupId}
                    onChange={(input) => setForm((current) => ({ ...current, animalGroupId: input.target.value }))}
                  >
                    <option value="">General ferme</option>
                    {animals.map((animal) => (
                      <option key={animal.id} value={animal.id}>
                        {animal.identificationNumber} - {animal.species}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="field">
                  <span>Type</span>
                  <select
                    value={form.eventType}
                    onChange={(input) =>
                      setForm((current) => ({
                        ...current,
                        eventType: input.target.value as SanitaryEventView['eventType']
                      }))
                    }
                  >
                    <option value="VACCINATION">Vaccination</option>
                    <option value="TRAITEMENT">Traitement</option>
                    <option value="CONSULTATION">Consultation</option>
                    <option value="MALADIE">Maladie</option>
                    <option value="MORTALITE">Mortalite</option>
                    <option value="CONTROLE">Controle</option>
                  </select>
                </label>
                <label className="field">
                  <span>Date</span>
                  <input
                    type="date"
                    value={form.eventDate}
                    onChange={(input) => setForm((current) => ({ ...current, eventDate: input.target.value }))}
                  />
                </label>
                <label className="field">
                  <span>Statut</span>
                  <select
                    value={form.status}
                    onChange={(input) =>
                      setForm((current) => ({
                        ...current,
                        status: input.target.value as SanitaryEventView['status']
                      }))
                    }
                  >
                    <option value="PLANIFIE">Planifie</option>
                    <option value="EN_COURS">En cours</option>
                    <option value="TERMINE">Termine</option>
                    <option value="CRITIQUE">Critique</option>
                  </select>
                </label>
                <label className="field">
                  <span>Notes</span>
                  <input
                    value={form.notes}
                    onChange={(input) => setForm((current) => ({ ...current, notes: input.target.value }))}
                  />
                </label>
              </div>
              <div className="module-inline-note">
                <span>Consigne une vaccination, une maladie, un traitement ou un controle.</span>
                <div className="hero-actions">
                  <Button className="module-submit-button sanitary-action-button sanitary-action-button-primary" type="submit" disabled={isPending}>
                    Enregistrer l'evenement
                  </Button>
                  <Button className="module-submit-button sanitary-action-button sanitary-action-button-secondary" variant="secondary" type="button" disabled={isPending} onClick={runCalendarSync}>
                    Synchroniser le calendrier auto
                  </Button>
                </div>
              </div>
            </form>
          </article>

          <article className="module-list-card sanitary-info-card sanitary-info-card-premium">
            <div className="dashboard-inline-actions">
              <div>
                <p className="eyebrow">Cadrage</p>
                <h2>Principes de supervision</h2>
              </div>
              <Badge variant="info">Lecture partagee</Badge>
            </div>
            <div className="metric-list">
              <span>Les statuts critiques alimentent automatiquement les alertes</span>
              <span>Les lots peuvent rester vides pour des actions generales ferme</span>
              <span>Le calendrier auto genere les rappels selon les protocoles</span>
            </div>
          </article>
        </section>
      ) : null}

      <section className="module-list-card sanitary-history-card sanitary-history-card-premium">
        <div className="dashboard-inline-actions">
          <div>
            <p className="eyebrow">Historique</p>
            <h2>Journal sanitaire</h2>
          </div>
          <Badge variant="info">{events.length} entree(s)</Badge>
        </div>
        {events.length ? (
          <div className="table-list sanitary-table-list">
            {events.map((item, index) => (
              <motion.article
                key={item.id}
                className={`table-row sanitary-table-row ${item.status === 'CRITIQUE' ? 'alert-critical' : item.status === 'TERMINE' ? 'alert-info' : 'alert-warning'}`}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.02 }}
              >
                <Badge variant={sanitaryBadge(item.status)}>{item.status}</Badge>
                <strong>{item.eventType}</strong>
                <span>{item.animalLabel || 'Ferme generale'}</span>
                <span>{new Date(item.eventDate).toLocaleDateString('fr-FR')}</span>
                <span>{item.isAutoGenerated ? `Auto - ${item.protocolLabel ?? 'Protocole'}` : 'Manuel'}</span>
                <span>{item.notes || 'Sans note'}</span>
                <span>Par {item.recordedByUserName}</span>
              </motion.article>
            ))}
          </div>
        ) : (
          <p>Aucun evenement sanitaire enregistre.</p>
        )}
      </section>
    </AppShell>
  );
}
